# Generated by Django 5.1.4 on 2024-12-17 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'Dólar Americano'), ('BRL', 'Real'), ('PYG', 'Guaraní'), ('ARS', 'Peso Argentino'), ('EUR', 'Euro')], max_length=100)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PAID', 'Paga'), ('PENDING', 'Pendente'), ('CANCELLED', 'Cancelada')], max_length=100)),
                ('is_recurring', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.useraccount')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.paymentmethod')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transactioncategory')),
            ],
        ),
    ]
